### ISSUE TITLE
Problem when I tried to deploy on Heroku

### ISSUE THREAD

**Issue by cyberboysumanjay** [diogotrentini/codebits#1]
Hey! I tried to deploy this app on Heroku. Build was successful and the app was deployed but when I opened the page I got this error

*The page you were looking for doesn't exist.
You may have mistyped the address or the page may have moved.
If you are the application owner check the logs for more information.*

Also I'm redirected to https://myappname.herokuapp.com/users/sign_in automatically!

**Comment by diogotrentini** [comment]
Hi, @cyberboysumanjay!

I've just deployed this app and it's working fine for me. The error you've described is the page for 500 errors (i.e., you may have accessed an invalid page). The redirection to `/users/sign_in` is intended: if you did not log in, you should see the sign in page.

If you still have problems, you could use `heroku logs -t` and search the logs for errors.
